#+STARTUP: indent

#+begin_src text

______       _   _   _           _     _
| ___ \     | | | | | |         | |   (_)
| |_/ / __ _| |_| |_| | ___  ___| |__  _ _ __
| ___ \/ _` | __| __| |/ _ \/ __| '_ \| | '_ \
| |_/ / (_| | |_| |_| |  __/\__ \ | | | | |_) |
\____/ \__,_|\__|\__|_|\___||___/_| |_|_| .__/
                                        | |      ______ ______ ______
                                        |_|     |______|______|______|


#+end_src

* Battleship

* What it is about?
This game targets all developers, no  matter the language they use.
The idea behind is to make each developer write small programs and get challenged against other developers.

* Game principle
It's a contest game. To win, players must shoot as much enemies as they can.
*NB: They are not shooting each others !!!*

* How to play
To play this game you must know about:

** Game architecture
The Battleship game is based on a REST client-server architecture.
The server side is already developed and hosts the game logic. It is available at this url:
[[http://battleship.dwlo.cloudbees.net]]. So all your requests will address that server.

** The REST API
This part is at your charge. You have to code your own REST client using the following APIs:

*** Start a new game play
This request is made once per game play and shared with other players as game identifier.
**** Method   : POST
**** URI      : /games
**** RESPONSE :
#+begin_src json
{
    "game-id": "32060218-5c1b-4b00-8b11-be49b1479c89"
}
#+end_src

*** Fire on the enemy
**** Method   : PUT
**** URI      : /games/game-id/players/player-id/fire
**** RESPONSE :
#+begin_src json
{
    "fire-status": "success|failure",
    "game-status": "running|over",
    "score": {
        "D": 1,
        "L": 1
    }
}
#+end_src
*** Show the battleship plan
**** Method   : GET
**** URI      : /games/game-id/battlefield
**** RESPONSE :
#+begin_src text
-|-|-|-|-
-|D|-|-|-
-|-|-|L|-
-|-|-|-|-
-|-|-|-|-
#+end_src

* CLIENTS
** BASH REST client (Default implementation)
This is a sample to quickly test the game and write your own client. Once
done you can share your implementation and send me a pull request.
Find the BASH REST client [[https://github.com/Dwlo/battleship/blob/master/bin/battleship-client][here]]
How to play ? Fetch the repository, go to the bin directory and execute the battleship-client
